# Generated by Django 3.2.18 on 2023-04-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa kategorii')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Odnośnik')),
                ('icon', models.ImageField(blank=True, upload_to='icons', verbose_name='Ikonka kategorii')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Odnośnik')),
                ('text', models.TextField(verbose_name='Treść')),
                ('date', models.DateTimeField(verbose_name='Data dodania')),
                ('wykop', models.CharField(blank=True, max_length=255, verbose_name='Wykop')),
                ('category', models.ManyToManyField(to='news.Category', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Wiadomość',
                'verbose_name_plural': 'Wiadomości',
            },
        ),
    ]
